FEATURES_MIRA = {
    "app_name": "mbw_mira",
    "label": "MBW Mira",
    "modules": [
        {
            "module_name": "MBW Mira",
            "label": "MBW Mira",
            "features": [
                # campagin
                {
                    "feature_name": "mira_campaign_full_access",
                    "label": "Truy cập chiến dịch đầy đủ",
                    "description": "Quản lý toàn bộ vòng đời của chiến dịch Mira.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Segment",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Data Source",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_creation",
                    "label": "Tạo chiến dịch",
                    "description": "Cho phép tạo chiến dịch mới và chỉnh sửa các chiến dịch đã tạo.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Segment",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Data Source",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_view_only",
                    "label": "Chỉ xem chiến dịch",
                    "description": "Cho phép chỉ xem thông tin chiến dịch, không được chỉnh sửa.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Segment",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Data Source",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_management",
                    "label": "Quản lý chiến dịch",
                    "description": "Quản lý trạng thái chiến dịch, cập nhật thông tin và theo dõi tiến độ.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Segment",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Data Source",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_file_management",
                    "label": "Quản lý file đính kèm chiến dịch",
                    "description": "Cho phép tải lên, xem và xóa file đính kèm trong chiến dịch.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "File",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_sharing",
                    "label": "Chia sẻ chiến dịch",
                    "description": "Cho phép chia sẻ chiến dịch với người khác qua email hoặc link.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_reporting",
                    "label": "Báo cáo chiến dịch",
                    "description": "Cho phép xem và xuất báo cáo về chiến dịch, thống kê hiệu suất.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Segment",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Data Source",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                # segment
                {
                    "feature_name": "mira_segment_full_access",
                    "label": "Truy cập Pool đầy đủ",
                    "description": "Quản lý toàn bộ vòng đời của Talent Pool (Segment).",
                    "permissions": [
                        {
                            "doctype": "Mira Segment",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_segment_creation",
                    "label": "Tạo Pool",
                    "description": "Cho phép tạo Talent Pool mới và chỉnh sửa các Pool đã tạo.",
                    "permissions": [
                        {
                            "doctype": "Mira Segment",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_segment_view_only",
                    "label": "Chỉ xem Pool",
                    "description": "Cho phép chỉ xem thông tin Talent Pool, không được chỉnh sửa.",
                    "permissions": [
                        {
                            "doctype": "Mira Segment",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_segment_management",
                    "label": "Quản lý Pool",
                    "description": "Quản lý Pool: cập nhật thông tin và theo dõi metrics.",
                    "permissions": [
                        {
                            "doctype": "Mira Segment",
                            "create": 0,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_segment_delete",
                    "label": "Xóa Pool",
                    "description": "Cho phép xóa Talent Pool (chỉ khi pool không còn talent).",
                    "permissions": [
                        {
                            "doctype": "Mira Segment",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_segment_reporting",
                    "label": "Báo cáo Pool",
                    "description": "Cho phép xem và xuất báo cáo về Pool, thống kê engagement và quality.",
                    "permissions": [
                        {
                            "doctype": "Mira Segment",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_segment_sync_ats",
                    "label": "Đồng bộ Pool từ ATS",
                    "description": "Cho phép đồng bộ Position từ ATS thành Talent Pool.",
                    "permissions": [
                        {
                            "doctype": "Mira Segment",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                # talent
                {
                    "feature_name": "mira_talent_full_access",
                    "label": "Truy cập Talent đầy đủ",
                    "description": "Quản lý toàn bộ vòng đời của Talent.",
                    "permissions": [
                        {
                            "doctype": "Mira Talent",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_talent_creation",
                    "label": "Tạo Talent",
                    "description": "Cho phép tạo Talent mới và chỉnh sửa các Talent đã tạo.",
                    "permissions": [
                        {
                            "doctype": "Mira Talent",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_talent_view_only",
                    "label": "Chỉ xem Talent",
                    "description": "Cho phép chỉ xem thông tin Talent, không được chỉnh sửa.",
                    "permissions": [
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_talent_management",
                    "label": "Quản lý Talent",
                    "description": "Quản lý Talent: cập nhật thông tin, status, và theo dõi interaction.",
                    "permissions": [
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_talent_delete",
                    "label": "Xóa Talent",
                    "description": "Cho phép xóa Talent.",
                    "permissions": [
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_talent_reporting",
                    "label": "Báo cáo Talent",
                    "description": "Cho phép xem và xuất báo cáo về Talent, thống kê và phân tích.",
                    "permissions": [
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_talent_import",
                    "label": "Import Talent",
                    "description": "Cho phép import Talent từ Excel hoặc CV.",
                    "permissions": [
                        {
                            "doctype": "Mira Talent",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_talent_export",
                    "label": "Export Talent",
                    "description": "Cho phép export danh sách Talent.",
                    "permissions": [
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                # campaign template
                {
                    "feature_name": "mira_campaign_template_full_access",
                    "label": "Truy cập Template chiến dịch đầy đủ",
                    "description": "Quản lý toàn bộ vòng đời của Campaign Template.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign Template",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Action Template",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Trigger Template",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_template_creation",
                    "label": "Tạo Template chiến dịch",
                    "description": "Cho phép tạo Campaign Template mới và chỉnh sửa.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign Template",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Action Template",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Trigger Template",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_template_view_only",
                    "label": "Chỉ xem Template chiến dịch",
                    "description": "Cho phép chỉ xem thông tin Campaign Template, không được chỉnh sửa.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 1,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Action Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Trigger Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_template_management",
                    "label": "Quản lý Template chiến dịch",
                    "description": "Quản lý Template: cập nhật thông tin, actions, triggers.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign Template",
                            "create": 0,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Action Template",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Trigger Template",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_template_delete",
                    "label": "Xóa Template chiến dịch",
                    "description": "Cho phép xóa Campaign Template.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_campaign_template_use",
                    "label": "Sử dụng Template chiến dịch",
                    "description": "Cho phép sử dụng Template để tạo Campaign mới.",
                    "permissions": [
                        {
                            "doctype": "Mira Campaign Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Action Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Trigger Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                }
            ],
        },
        {
            "name": "mira_interaction",
            "label": "Quản lý Tương tác (Mira Interaction)",
            "description": "Quản lý tương tác của talent với các chiến dịch marketing và recruitment",
            "features": [
                {
                    "feature_name": "mira_interaction_full_access",
                    "label": "Toàn quyền quản lý Tương tác",
                    "description": "Cho phép toàn quyền quản lý Mira Interaction bao gồm tạo, xem, sửa, xóa, xuất, báo cáo.",
                    "permissions": [
                        {
                            "doctype": "Mira Interaction",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Email Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_interaction_creation",
                    "label": "Tạo Tương tác",
                    "description": "Cho phép tạo mới Mira Interaction.",
                    "permissions": [
                        {
                            "doctype": "Mira Interaction",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Email Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_interaction_view_only",
                    "label": "Chỉ xem Tương tác",
                    "description": "Cho phép chỉ xem thông tin Mira Interaction, không được chỉnh sửa.",
                    "permissions": [
                        {
                            "doctype": "Mira Interaction",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Email Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_interaction_management",
                    "label": "Quản lý Tương tác",
                    "description": "Cho phép xem và chỉnh sửa Mira Interaction, không bao gồm xóa.",
                    "permissions": [
                        {
                            "doctype": "Mira Interaction",
                            "create": 0,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Email Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_interaction_delete",
                    "label": "Xóa Tương tác",
                    "description": "Cho phép xóa Mira Interaction.",
                    "permissions": [
                        {
                            "doctype": "Mira Interaction",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Email Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_interaction_reporting",
                    "label": "Báo cáo Tương tác",
                    "description": "Cho phép xem và tạo báo cáo về Mira Interaction.",
                    "permissions": [
                        {
                            "doctype": "Mira Interaction",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Email Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_interaction_analytics",
                    "label": "Phân tích Tương tác",
                    "description": "Cho phép xem và phân tích dữ liệu tương tác chi tiết.",
                    "permissions": [
                        {
                            "doctype": "Mira Interaction",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "Mira Talent",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Email Template",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                }
            ],
        },
        {
            "name": "mira_action",
            "label": "Quản lý Hành động (Mira Action)",
            "description": "Quản lý các hành động trong chiến dịch marketing và recruitment",
            "features": [
                {
                    "feature_name": "mira_action_full_access",
                    "label": "Toàn quyền quản lý Hành động",
                    "description": "Cho phép toàn quyền quản lý Mira Action bao gồm tạo, xem, sửa, xóa, xuất, báo cáo.",
                    "permissions": [
                        {
                            "doctype": "Mira Action",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 1,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign Social",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_action_creation",
                    "label": "Tạo Hành động",
                    "description": "Cho phép tạo mới Mira Action.",
                    "permissions": [
                        {
                            "doctype": "Mira Action",
                            "create": 1,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign Social",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_action_view_only",
                    "label": "Chỉ xem Hành động",
                    "description": "Cho phép chỉ xem thông tin Mira Action, không được chỉnh sửa.",
                    "permissions": [
                        {
                            "doctype": "Mira Action",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 1,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign Social",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_action_management",
                    "label": "Quản lý Hành động",
                    "description": "Cho phép xem và chỉnh sửa Mira Action, không bao gồm xóa.",
                    "permissions": [
                        {
                            "doctype": "Mira Action",
                            "create": 0,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 1,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign Social",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_action_delete",
                    "label": "Xóa Hành động",
                    "description": "Cho phép xóa Mira Action.",
                    "permissions": [
                        {
                            "doctype": "Mira Action",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 1,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign Social",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_action_reporting",
                    "label": "Báo cáo Hành động",
                    "description": "Cho phép xem và tạo báo cáo về Mira Action.",
                    "permissions": [
                        {
                            "doctype": "Mira Action",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 1,
                            "report": 1
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign Social",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                },
                {
                    "feature_name": "mira_action_execution",
                    "label": "Thực thi Hành động",
                    "description": "Cho phép thực thi và cập nhật trạng thái Mira Action.",
                    "permissions": [
                        {
                            "doctype": "Mira Action",
                            "create": 0,
                            "read": 1,
                            "write": 1,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 1,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "User",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Talent Campaign",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        },
                        {
                            "doctype": "Mira Campaign Social",
                            "create": 0,
                            "read": 1,
                            "write": 0,
                            "delete": 0,
                            "submit": 0,
                            "cancel": 0,
                            "amend": 0,
                            "email": 0,
                            "print": 0,
                            "share": 0,
                            "export": 0,
                            "report": 0
                        }
                    ],
                    "module_name": "MBW Mira"
                }
            ],
        },
    ],
}
